"""Adicionando a relationship da tabela Pedido com PedidoItens

Revision ID: 758de1d97fe7
Revises: 052d3c68751d
Create Date: 2026-01-13 09:30:04.838878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758de1d97fe7'
down_revision: Union[str, Sequence[str], None] = '052d3c68751d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
